version: '3'

services:

  api:
    container_name: api
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./api
    ports:
      - 3000:3000
    links:
      - mysql
      - redis
    environment:
      WAIT_HOSTS: mysql:3306

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379
    env_file: .env
    volumes:
      - redis_data:/var/lib/redis
      
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local